image: maven:3.8.4-openjdk-17-slim

variables:
  ALLURE_RESULTS: "target/allure-results"
  ALLURE_REPORT: "target/site/allure-maven"

stages:
  - test
  - report

test:
  stage: test
  before_script:
    - mkdir -p ${ALLURE_RESULTS}
    - mkdir -p public
    - mkdir -p public/history
    - apt-get update && apt-get install -y unzip
#    - 'curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: $MY_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=pages"'
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp -r public/history ${ALLURE_RESULTS}
  script:
    - mvn test
  after_script:
    - mvn allure:report
  allow_failure: true
  artifacts:
    when: always
    paths:
      - ${ALLURE_REPORT}
    expire_in: 1 days

pages:
  stage: report
  needs:
    - test
  script:
    - cp -r ${ALLURE_REPORT}* public
  artifacts:
    when: always
    paths:
      - public/
    expire_in: never